### ISSUE TITLE
mistake in install react 

### ISSUE THREAD

**Issue by HamzaAbdrahim** [parin-prog/eCommerce_MERN_app#2]
Hi,ther is a mistake in install  react app you shold not use create-react-app instad use vite to install  your react app cuz the react team  no longer recommend using create-react-app. I recommend you to read this artic(https://www.linkedin.com/pulse/bye-create-react-app-get-started-react-using-vitejs-apoorve-verma-/),hope it helps ♥

**Comment by parin-prog** [comment]
it's okay np
